### ISSUE TITLE
iOS and Android compatibility

### ISSUE THREAD

**Issue by dustinkerstein** [chrmi/unity-webvr#4]
I was just curious if you were able to get this working on iOS / Android. The demo scene appears to work fine in Chrome, Firebox, and Edge (compiled in Unity 2017.1.2p2) but I haven't been able to get past the loading screen on iOS Mobile Safari or Android Chrome. I see these requests in the Dev Console Network Tab: 

![image](https://user-images.githubusercontent.com/7659306/32445359-79f3d27c-c2d3-11e7-917b-5b97aee45362.png)

But then nothing after, and also nothing output in the console.

**Comment by alexpareto** [comment]
This looks to be a problem with Unity rather than the package. If you strip away the Loading screen you'll get this: 
![img_1792](https://user-images.githubusercontent.com/1837291/32529831-88b593be-c3ef-11e7-8f3c-5805476fa932.jpg)

Clicking 'Ok' renders the project for a few seconds before it crashes. Looks like Unity isn't very supportive of Mobile browsers for WebGL right now.

**Comment by dustinkerstein** [comment]
Yah, that seems to be the case. Thanks.
